server:
  port: 8888
spring:
  application:
    name: getAway-model
  cloud:
    gateway:
      discovery:
        locator:
          ####开启以服务id去注册中心上获取转发地址
          enabled: true
          lower-case-service-id: true
      routes:
      - id: login-model
        uri: lb://login-model
        predicates:
        - Path=/auth/**
        filters:
        - StripPrefix=1
      - id: forum-model
        uri: lb://forum-model
        predicates:
        - Path=/forum/**
        filters:
        - StripPrefix=1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
