spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: ENC(QsiUur6Y77CVRtlmi9AROUXsMAia4O2z)
    database: 5
    lettuce:
      pool:
        max-active: 10
        min-idle: 5
        max-idle: 10
        max-wait: 5s