server:
  port: 8881
spring:
  application:
    name: forum-model
  datasource:
    url: jdbc:mysql://localhost:3306/completed_project?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: ENC(QsiUur6Y77CVRtlmi9AROUXsMAia4O2z)
    driverClassName: com.mysql.cj.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis-plus:
  configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
#logging:
#  level:
#    per.zs.login.db.mapper: debug
jasypt:
  encryptor:
    password: myproject